### ISSUE TITLE
[OZ: N-02] Multiple conditions for error handling statements

### ISSUE THREAD

**Issue by ggviana** [pods-finance/yield-contracts#86]
Throughout the codebase there are require statements and custom error blocks that need multiple conditions to be satisfied. For instance:

* In the constructor of the `ETHAdapter` contract there is a require statement that checks if coin 0 from the pool is equal to the `ETH` address and if coin 1 is equal to `stETH` address. If one of the conditions is not met, there is no error message to indicate why the transaction was reverted.
* The `migrate` function in the `BaseVault` contract has a conditional block that checks if the vault is not allowed and if the destination vault does not have the same underlying asset as the current vault. Although the custom error that is thrown is not wrong, it might be better if these two validations are separated to return more specific error messages.
* The `onlyRoundStarter` modifier has a custom error block that checks if less than a week has passed since the last end round and if the caller is different from the controller.If the conditions are met, the error returned is that the caller is not the controller. Consider separating both conditions in order to throw a more specific error message.

To simplify the codebase and to raise the most helpful error messages for failing blocks,consider having a single require statement with an appropriate error message or a single custom error block per condition.

**Comment by Robsonsjre** [comment]
We are not doing this issue because of prioritization and time constrains.
